# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingName', models.TextField(db_column='trading_name')),
                ('ownerName', models.TextField(db_column='owner_name')),
                ('document', models.CharField(max_length=14, unique=True)),
                ('coverageArea', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='coverage_area', srid=4326)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
